# Generated by Django 4.0.4 on 2022-04-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('💫 РАМАДАН СЕТ', '💫 РАМАДАН СЕТ'), ('set_zavtrak', '🍳 Сеты на завтрак'), ('set_napitki', '🍔🍟🥤 Сеты'), ('stan_burger', '🍔 Стандартные бургеры'), ('prem_burger', '🍔 Премиум бургеры'), ('chiken_set', '🍗 Куриные блюда'), ('souce', '🧀 Соусы'), ('sneki', '🍟 Снеки'), ('salat', '🥗 Салаты'), ('decert', '🍰 Десерты'), ('hol_napitki', '☕ Горячие напитки'), ('gor_napitki', '🧋 Холодные напитки'), ('klassik_napitki', '🥤 Классические напитки')], max_length=250),
        ),
    ]
