# Generated by Django 4.0.4 on 2022-04-29 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choise', to='main.product')),
            ],
        ),
    ]
