# Generated by Django 4.0.4 on 2022-04-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='about',
            new_name='about1',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name1',
        ),
    ]
