# Generated by Django 4.0.4 on 2022-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default='Скоро мы сюда добавим блюда!'),
        ),
    ]
